trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: Npm@1
  inputs:
    verbose: false
  displayName: 'Install dependencies'
- task: Npm@1
  inputs:
    command: custom
    customCommand: 'run compile'
    verbose: false
    displayName: 'Compile sources'
